# 启动云原生开发环境的配置（控制开发环境如何启动）
$:
  vscode:
    - docker:

        image: docker.cnb.cool/iiistudio/os/docker/python:3.12.11
      services:
        - vscode
        - docker

main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/IIIStudio/key/-/blob/main/github/env.yml
      stages:
        - name: 同步到GitHub
          image: tencentcom/git-sync 
          settings:
            target_url: https://github.com/IIIStudio/MSTTS.git
            auth_type: https
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL} 
            username: ${GIT_USERNAME} 
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            sync_mode: mirror  # 镜像模式，直接覆盖
            force: true